### ISSUE TITLE
之前看到的一个类似的 Repo

### ISSUE THREAD

**Issue by district10** [letiantian/paste-as-markdown#1]
[euangoddard/clipboard2markdown: Convert rich-text on your clipbaord to markdown](https://github.com/euangoddard/clipboard2markdown)。

---

By the way，我也是看到简书的黑科技才搜索这东西的。实在太有用！尤其是拷贝 Wikipedia 的内容的时候。

**Comment by letiantian** [comment]
不错，感谢分享。 已经添加到README.md
